lang: fr-FR
title: <br><br>PORTFOLIO<br><br>
description: Ingénieure Agroalimentaire <br>&<br> Data Scientist<br><br>
baseurl: "" # laisser vide pour GitHub Pages
url: "https://emma-dcs.github.io"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
email: emma.dacslv@gmail.com
github: https://github.com/emma-dcs
linkedin: https://www.linkedin.com/in/emma-d-352a37211
footer_text: ""
header_pages:
  - about.md
  - competence.md
  - service.md
  - projets.md
  - contact.md